### ISSUE TITLE
React native admob not working after updating !!

### ISSUE THREAD

**Issue by softsstar** [sbugert/react-native-admob#448]
getting annotation null error on newer reactnative version 

> Configure project :react-native-admob
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.0.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-admob:compileDebugJavaWithJavac FAILED
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobInterstitialAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:119: error: cannot find symbol
    private void sendEvent(String name, @Nullable WritableMap event) {
                                         ^
  symbol:   class Nullable
  location: class ReactAdView
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:196: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNAdMobBannerViewManager
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:254: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNAdMobBannerViewManager
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobInterstitialAdModule.java:103: error: cannot find symbol
    private void sendEvent(String eventName, @Nullable WritableMap params) {
                                              ^
  symbol:   class Nullable
  location: class RNAdMobInterstitialAdModule
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:123: error: cannot find symbol
    private void sendEvent(String eventName, @Nullable WritableMap params) {
                                              ^
  symbol:   class Nullable
  location: class RNAdMobRewardedVideoAdModule
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:122: error: cannot find symbol
    private void sendEvent(String name, @Nullable WritableMap event) {
                                         ^
  symbol:   class Nullable
  location: class ReactPublisherAdView
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:229: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNPublisherBannerViewManager
D:\React Native\admo\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:302: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNPublisherBannerViewManager
12 errors

**Comment by Linrasis** [comment]
Same issue :/

**Comment by ndejesus1227** [comment]
Same issue

**Comment by IacoCesar** [comment]
Same issue RN 0.60

**Comment by IacoCesar** [comment]
Solved adding

`configurations.all {
    resolutionStrategy {
        force "com.google.android.gms:play-services-basement:16.0.1"
        force "com.google.android.gms:play-services-base:16.0.1"
        force "com.google.android.gms:play-services-stats:16.0.1"
        force "com.google.android.gms:play-services-gcm:16.0.0"
        force "com.google.android.gms:play-services-ads:16.0.1"
    }
}
`

`implementation (project(':react-native-admob'), {
      exclude group: "com.google.android.gms"
 })`

But have other error
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;`

**Comment by mallmann-objective** [comment]
@IacoCesar Where should I put this configuration? Is it in the `build.gradle` file?

**Comment by IacoCesar** [comment]
> @IacoCesar Where should I put this configuration? Is it in the `build.gradle` file?

Yes put the implementation in dependencies and configurations.all in upper of dependencies

**Comment by mallmann-objective** [comment]
> > @IacoCesar Where should I put this configuration? Is it in the `build.gradle` file?
> 
> Yes put the implementation in dependencies and configurations.all in upper of dependencies

Sorry, I'm still confused about the gradle file. Am I missing something?

![Screen Shot 2019-06-25 at 11 55 39](https://user-images.githubusercontent.com/49730125/60109146-35edf880-9740-11e9-8e16-a606bf9e7e53.png)

**Comment by IacoCesar** [comment]
> > > @IacoCesar Where should I put this configuration? Is it in the `build.gradle` file?
> > 
> > 
> > Yes put the implementation in dependencies and configurations.all in upper of dependencies
> 
> Sorry, I'm still confused about the gradle file. Am I missing something?
> 
> ![Screen Shot 2019-06-25 at 11 55 39](https://user-images.githubusercontent.com/49730125/60109146-35edf880-9740-11e9-8e16-a606bf9e7e53.png)

build.gradle of the android/app

**Comment by SagaRPate** [comment]
> **### Same issue in react-native": "0.59.9"**
> **### react": "16.8.3"**

**Comment by a26364177** [comment]
Same issue in "react-native": "0.59.9"
"react": "16.8.3"

**Comment by ank26oct** [comment]
Go to:

https://github.com/sbugert/react-native-admob/issues/452#issuecomment-506705969

**Comment by amixel** [comment]
same issue

**Comment by bishrulhaq** [comment]
Go to **react-native-admob** under node-modules and change "import android.support.annotation.Nullable;" to import androidx.annotation.Nullable;

**Comment by MatheusAlvesA** [comment]
I fixed this issue on my own lib.
Check this: https://github.com/sbugert/react-native-admob/issues/458

**Comment by vammu920** [comment]
> Solved adding
> 
> `configurations.all { resolutionStrategy { force "com.google.android.gms:play-services-basement:16.0.1" force "com.google.android.gms:play-services-base:16.0.1" force "com.google.android.gms:play-services-stats:16.0.1" force "com.google.android.gms:play-services-gcm:16.0.0" force "com.google.android.gms:play-services-ads:16.0.1" } } `
> 
> `implementation (project(':react-native-admob'), { exclude group: "com.google.android.gms" })`
> 
> But have other error
> `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;`
> 
> UPDATE
> 
> add `implementation ('com.google.android.gms:play-services-ads:16.+') { force = true; }` WORKS!

**Comment by koenpunt** [comment]
I've opened a PR to bring this library up to date with the latest version of React Native, and thus bringing support for CocoaPods and support for Android X: #472

**Comment by koenpunt** [comment]
The latest beta (`v2.0.0-beta.6`) should work just fine with the latest version of React Native (and thus AndroidX)

**Comment by thedevxen** [comment]
> The latest beta (`v2.0.0-beta.6`) should work just fine with the latest version of React Native (and thus AndroidX)

it's not working on 2.0.0-beta.6, I just initiated fresh react-native project, and first module I installed was react-native-admob.

**Comment by koenpunt** [comment]
I need a little bit more than just "it's not working". As you can see in the example project it is working, so I think it's a matter of configuration.

**Comment by vlerants** [comment]
I switched from `import android.support.annotation.Nullable;` to `import androidx.annotation.Nullable;` on these files:

- RNAdMobBannerViewManager.java

- RNAdMobInterstitialAdModule.java

- RNAdMobRewardedVideoAdModule.java

-RNPublisherBannerViewManager.java

and it worked for me.

I hope this helps.



``

**Comment by hugoh59** [comment]
I already have it like that but still throw error message.

**Comment by AftabUfaq** [comment]
have the same issue on m project. apply all the above but get nothing . same erroe

**Comment by Nishkarshgithub** [comment]
Stuck on this for about 7 hours and finally found the solution which is pretty simple. Just upgrade `react-native-admob` to v2.0.0-beta.6 using

My react-native project config...

- "react": "16.9.0",
- "react-native": "0.61.5",
- "react-native-admob": "^2.0.0-beta.6",

Install by using..

> npm install react-native-admob@2.0.0-beta.6

First, create a Google Admob account and create you app in it and copy App_ID from GoogleAdmob > Apps > View All Apps > Copy AppID.

and then edit your AndroidManifest file.  Project > android > app > src >  AndroidManifest .

under <application> tag insert

<meta-data 
        android:name="com.google.android.gms.ads.APPLICATION_ID" 
        android:value="**YOUR_APP_ID**"/>
>
**note**: please add your app id in android.value

Now clean your build folder and rebuild the project everything will work fine.

**Comment by UserSina** [comment]
> Stuck on this for about 7 hours and finally found the solution which is pretty simple. Just upgrade `react-native-admob` to v2.0.0-beta.6 using
> 
> My react-native project config...
> 
> * "react": "16.9.0",
> * "react-native": "0.61.5",
> * "react-native-admob": "^2.0.0-beta.6",
> 
> Install by using..
> 
> > npm install react-native-admob@2.0.0-beta.6
> 
> First, create a Google Admob account and create you app in it and copy App_ID from GoogleAdmob > Apps > View All Apps > Copy AppID.
> 
> and then edit your AndroidManifest file. Project > android > app > src > AndroidManifest .
> 
> under tag insert
> 
> ```
> <meta-data 
>         android:name="com.google.android.gms.ads.APPLICATION_ID" 
>         android:value="**YOUR_APP_ID**"/>
> >
> ```
> 
> **note**: please add your app id in android.value
> 
> Now clean your build folder and rebuild the project everything will work fine.

I've had another error after solving the previous one with this code. I had to add the following code in android/app/build.gradle for it to finally work:
`android {
    defaultConfig {
        ...
        minSdkVersion 15 
        targetSdkVersion 28
        multiDexEnabled true
    }
    ...
}

dependencies {
  implementation 'com.android.support:multidex:1.0.3'
}`

Source: [https://developer.android.com/studio/build/multidex](This)

**Comment by kanyo33** [comment]
> > Stuck on this for about 7 hours and finally found the solution which is pretty simple. Just upgrade `react-native-admob` to v2.0.0-beta.6 using
> > My react-native project config...
> > 
> > * "react": "16.9.0",
> > * "react-native": "0.61.5",
> > * "react-native-admob": "^2.0.0-beta.6",
> > 
> > Install by using..
> > > npm install react-native-admob@2.0.0-beta.6
> > 
> > 
> > First, create a Google Admob account and create you app in it and copy App_ID from GoogleAdmob > Apps > View All Apps > Copy AppID.
> > and then edit your AndroidManifest file. Project > android > app > src > AndroidManifest .
> > under tag insert
> > ```
> > <meta-data 
> >         android:name="com.google.android.gms.ads.APPLICATION_ID" 
> >         android:value="**YOUR_APP_ID**"/>
> > >
> > ```
> > 
> > 
> > **note**: please add your app id in android.value
> > Now clean your build folder and rebuild the project everything will work fine.
> 
> I've had another error after solving the previous one with this code. I had to add the following code in android/app/build.gradle for it to finally work:
> `android {
> defaultConfig {
> ...
> multiDexEnabled true
> }
> ...
> }
> 
> dependencies {
> implementation 'com.android.support:multidex:1.0.3'
> }`
> 
> Source: [https://developer.android.com/studio/build/multidex](This)

Can attest to the multidex error being a common issue with this plugin. This workaround did the job. Thanks.

**Comment by sergenti** [comment]
same issue, I implemented Admob using _@react-native-firebase/app_ and  _@react-native-firebase/admob_  btw I would really like to use this library, Ad-components are such a better implementation

**Comment by omprakash8080** [comment]
Update the file :- Build.gradle(react-native-admob)

//    implementation 'com.google.android.gms:play-services-ads:+' // comment this line

implementation 'com.google.android.gms:play-services-ads:19.7.0' // add this line.

**Comment by sarceda** [comment]
> Update the file :- Build.gradle(react-native-admob)
> 
> // implementation 'com.google.android.gms:play-services-ads:+' // comment this line
> 
> implementation 'com.google.android.gms:play-services-ads:19.7.0' // add this line.

This, and other variations in the 'com.google.android.gms:play-services-ads:' implementation works, and I can build my app.

The problem is than then there is a great amount of "crashes" with this message:

```
java.lang.IllegalStateException
com.sbugert.rnadmob.ReactAdView.setAdSize
```

This is the Stack trace. Any idea on what to look for?

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: 
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:98)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:131)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:51)
  at com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:46)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties (NativeViewHierarchyManager.java:139)
  at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute (UIViewOperationQueue.java:93)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:844)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:952)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2200 (UIViewOperationQueue.java:44)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1012)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:172)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:84)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1090)
  at android.view.Choreographer.doCallbacks (Choreographer.java:893)
  at android.view.Choreographer.doFrame (Choreographer.java:809)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1078)
  at android.os.Handler.handleCallback (Handler.java:907)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:83)
Caused by: java.lang.IllegalStateException: 
  at com.google.android.gms.internal.ads.zzzn.setAdSizes
  at com.google.android.gms.ads.BaseAdView.setAdSize
  at com.google.android.gms.ads.AdView.setAdSize
  at com.sbugert.rnadmob.ReactAdView.setAdSize (RNAdMobBannerViewManager.java:158)
  at com.sbugert.rnadmob.RNAdMobBannerViewManager.setPropAdSize (RNAdMobBannerViewManager.java:216)
```

**Comment by abhisheq6u** [comment]
> 
> 
> Update the file :- Build.gradle(react-native-admob)
> 
> // implementation 'com.google.android.gms:play-services-ads:+' // comment this line
> 
> implementation 'com.google.android.gms:play-services-ads:19.7.0' // add this line.

This worked for me straight away!! Thanks to @omprakash8080

**Comment by ghost** [comment]
Has this issue been resolved?
I try do like https://github.com/sbugert/react-native-admob/issues/448#issuecomment-814028706 or like https://github.com/sbugert/react-native-admob/issues/448#issuecomment-537659889, but them don't work for me, usage issue doesn't change.
```json
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-admob": "^2.0.0-beta.6",
```

**Comment by varolemre** [comment]
Worst npm package i have ever seen. It's sad that there is no alternative

**Comment by koenpunt** [comment]
> Worst npm package i have ever seen. It's sad that there is no alternative

It's open source, feel free to improve it yourself.

**Comment by Salman98** [comment]
> Go to **react-native-admob** under node-modules and change "import android.support.annotation.Nullable;" to import androidx.annotation.Nullable;

after using the above changes and adding these line in react-native-admob@2.0.0-beta.6 **build.gradle** file ,  I'm able to resolve this issue  

```
 implementation ('com.google.android.gms:play-services-ads:19.6.0') { force = true; }
 ```
