### ISSUE TITLE
Cannot find symbol cannot find symbol:  method toArrayList()

### ISSUE THREAD

**Issue by fdobre** [sbugert/react-native-admob#231]
React-native 0.50.4,   react-native-admob 2.0.0-beta.3,

When trying to build with react-native run-android:

I get 5 errors likes this (for each file in /rnadmob):
`/node_modules/react-native-admob/android/src/main/java/com/sbugert/rnadmob/RNAdMobInterstitialAdModule.java:117: error: cannot find symbol
        ArrayList<Object> list = nativeArray.toArrayList();
                                            ^
  symbol:   method toArrayList()
  location: variable nativeArray of type ReadableNativeArray`

This happened after an update from 1.3.2 to  react-native-admob 2.0.0-beta.3 and an update of react-native from 0.45 to 0.50.
Am I doing something wrong?

I ran react-native link, cleaned cache etc.

Please advise.

Any advice or suggestion will be greatly appreciated.
I added a question on stackoverflow too:
https://stackoverflow.com/questions/47887443/android-react-native-admob-error-cannot-find-symbol-toarraylist

IOS building works ok.

**Comment by nbucciarelli** [comment]
@fdobre - I encountered this same issue and just rebuilt the `node_modules` and `android` folders.

```
$ rm -rf node_modules
$ rm -rf android
$ yarn
$ react-native link
$ yarn android
```

Rebuilding all of that seemed to fix everything.

**Comment by fdobre** [comment]
I tried removing node_modules and re-linking but it didn't work. When downgrading to 1.3.2 the error disappears.

I also tried to upgrade RN to 0.51.0 and the issues persists in this version too.

**Comment by amorenew** [comment]
@fdobre I think your android project still have the old linking.
You should open your project in android studio and check your main activity class
My answer to you on stackoverflow

**Comment by fdobre** [comment]
I found it was a gradle issue, not a react-native-admob problem.
I fixed it with changing the react native url from gradle file.
More details here: 
https://stackoverflow.com/questions/47887443/android-react-native-admob-error-cannot-find-symbol-toarraylist?answertab=active

**Comment by endel** [comment]
I'm having this error too. `react-native@0.55.3`

**Comment by zaferatli** [comment]
any update
