### ISSUE TITLE
Error while building android build: Method does not override or implement a method from a supertype 

### ISSUE THREAD

**Issue by rohitgoyal** [sbugert/react-native-admob#169]
Hi while I am trying to run react-native run-android.
It is failing to build the app with following exception. 
It was working with react-native version 0.44 but the issue is happening with the latest version (0.47.1)
> /psych/node_modules/react-native-admob/android/src/main/java/com/sbugert/rnadmob/RNAdMobPackage.java:24: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> 1 error
> :react-native-admob:compileReleaseJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-admob:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 

Following are the versions I am using.
```
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.1",
    "react-native-admob": "^1.3.0",
    "react-native-fcm": "^7.5.1",
```

**Comment by koenpunt** [comment]
There’s an open pull request for this issue; https://github.com/sbugert/react-native-admob/pull/164 But I’m still waiting to hear back from the author.

**Comment by koenpunt** [comment]
Fixed now #164 is merged
